#############################################################################
# Makefile for building: WaterPump
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  WaterPump.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile WaterPump.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I. -I. -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = WaterPump1.0.0
DISTDIR = /home/ttu/WaterPump/.tmp/WaterPump1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/aarch64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/aarch64-linux-gnu/libQt6Widgets.so /usr/lib/aarch64-linux-gnu/libQt6Gui.so /usr/lib/aarch64-linux-gnu/libGLX.so /usr/lib/aarch64-linux-gnu/libOpenGL.so /usr/lib/aarch64-linux-gnu/libQt6SerialPort.so /usr/lib/aarch64-linux-gnu/libQt6Network.so /usr/lib/aarch64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		controlboardinterface.cpp \
		basestationinterface.cpp \
		maintab.cpp \
		settingstab.cpp \
		tagstab.cpp \
		welcometab.cpp \
		newbottle.cpp \
		onscreenkeypad.cpp \
		onscreenkeyboard.cpp \
		waterusagetab.cpp moc_mainwindow.cpp \
		moc_controlboardinterface.cpp \
		moc_basestationinterface.cpp \
		moc_maintab.cpp \
		moc_settingstab.cpp \
		moc_tagstab.cpp \
		moc_welcometab.cpp \
		moc_newbottle.cpp \
		moc_onscreenkeypad.cpp \
		moc_onscreenkeyboard.cpp \
		moc_waterusagetab.cpp
OBJECTS       = main.o \
		mainwindow.o \
		controlboardinterface.o \
		basestationinterface.o \
		maintab.o \
		settingstab.o \
		tagstab.o \
		welcometab.o \
		newbottle.o \
		onscreenkeypad.o \
		onscreenkeyboard.o \
		waterusagetab.o \
		moc_mainwindow.o \
		moc_controlboardinterface.o \
		moc_basestationinterface.o \
		moc_maintab.o \
		moc_settingstab.o \
		moc_tagstab.o \
		moc_welcometab.o \
		moc_newbottle.o \
		moc_onscreenkeypad.o \
		moc_onscreenkeyboard.o \
		moc_waterusagetab.o
DIST          = /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf \
		WaterPump.pro mainwindow.h \
		controlboardinterface.h \
		basestationinterface.h \
		maintab.h \
		settingstab.h \
		tagstab.h \
		welcometab.h \
		newbottle.h \
		onscreenkeypad.h \
		onscreenkeyboard.h \
		waterusagetab.h main.cpp \
		mainwindow.cpp \
		controlboardinterface.cpp \
		basestationinterface.cpp \
		maintab.cpp \
		settingstab.cpp \
		tagstab.cpp \
		welcometab.cpp \
		newbottle.cpp \
		onscreenkeypad.cpp \
		onscreenkeyboard.cpp \
		waterusagetab.cpp
QMAKE_TARGET  = WaterPump
DESTDIR       = 
TARGET        = WaterPump


first: all
####### Build rules

WaterPump: ui_mainwindow.h ui_maintab.h ui_settingstab.h ui_tagstab.h ui_welcometab.h ui_newbottle.h ui_onscreenkeypad.h ui_onscreenkeyboard.h ui_waterusagetab.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WaterPump.pro /usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf \
		WaterPump.pro \
		/usr/lib/aarch64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Gui.prl \
		/usr/lib/aarch64-linux-gnu/libQt6SerialPort.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Network.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile WaterPump.pro
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf:
WaterPump.pro:
/usr/lib/aarch64-linux-gnu/libQt6Widgets.prl:
/usr/lib/aarch64-linux-gnu/libQt6Gui.prl:
/usr/lib/aarch64-linux-gnu/libQt6SerialPort.prl:
/usr/lib/aarch64-linux-gnu/libQt6Network.prl:
/usr/lib/aarch64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile WaterPump.pro

qmake_all: FORCE


all: Makefile WaterPump

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h controlboardinterface.h basestationinterface.h maintab.h settingstab.h tagstab.h welcometab.h newbottle.h onscreenkeypad.h onscreenkeyboard.h waterusagetab.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp controlboardinterface.cpp basestationinterface.cpp maintab.cpp settingstab.cpp tagstab.cpp welcometab.cpp newbottle.cpp onscreenkeypad.cpp onscreenkeyboard.cpp waterusagetab.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui maintab.ui settingstab.ui tagstab.ui welcometab.ui newbottle.ui onscreenkeypad.ui onscreenkeyboard.ui waterusagetab.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_controlboardinterface.cpp moc_basestationinterface.cpp moc_maintab.cpp moc_settingstab.cpp moc_tagstab.cpp moc_welcometab.cpp moc_newbottle.cpp moc_onscreenkeypad.cpp moc_onscreenkeyboard.cpp moc_waterusagetab.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_controlboardinterface.cpp moc_basestationinterface.cpp moc_maintab.cpp moc_settingstab.cpp moc_tagstab.cpp moc_welcometab.cpp moc_newbottle.cpp moc_onscreenkeypad.cpp moc_onscreenkeyboard.cpp moc_waterusagetab.cpp
moc_mainwindow.cpp: mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_controlboardinterface.cpp: controlboardinterface.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include controlboardinterface.h -o moc_controlboardinterface.cpp

moc_basestationinterface.cpp: basestationinterface.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include basestationinterface.h -o moc_basestationinterface.cpp

moc_maintab.cpp: maintab.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include maintab.h -o moc_maintab.cpp

moc_settingstab.cpp: settingstab.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include settingstab.h -o moc_settingstab.cpp

moc_tagstab.cpp: tagstab.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include tagstab.h -o moc_tagstab.cpp

moc_welcometab.cpp: welcometab.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include welcometab.h -o moc_welcometab.cpp

moc_newbottle.cpp: newbottle.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include newbottle.h -o moc_newbottle.cpp

moc_onscreenkeypad.cpp: onscreenkeypad.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include onscreenkeypad.h -o moc_onscreenkeypad.cpp

moc_onscreenkeyboard.cpp: onscreenkeyboard.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include onscreenkeyboard.h -o moc_onscreenkeyboard.cpp

moc_waterusagetab.cpp: waterusagetab.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/ttu/WaterPump/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/ttu/WaterPump -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtSerialPort -I/usr/include/aarch64-linux-gnu/qt6/QtNetwork -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include waterusagetab.h -o moc_waterusagetab.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_maintab.h ui_settingstab.h ui_tagstab.h ui_welcometab.h ui_newbottle.h ui_onscreenkeypad.h ui_onscreenkeyboard.h ui_waterusagetab.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_maintab.h ui_settingstab.h ui_tagstab.h ui_welcometab.h ui_newbottle.h ui_onscreenkeypad.h ui_onscreenkeyboard.h ui_waterusagetab.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic mainwindow.ui -o ui_mainwindow.h

ui_maintab.h: maintab.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic maintab.ui -o ui_maintab.h

ui_settingstab.h: settingstab.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic settingstab.ui -o ui_settingstab.h

ui_tagstab.h: tagstab.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic tagstab.ui -o ui_tagstab.h

ui_welcometab.h: welcometab.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic welcometab.ui -o ui_welcometab.h

ui_newbottle.h: newbottle.ui \
		/usr/lib/qt6/libexec/uic \
		onscreenkeyboard.h \
		onscreenkeypad.h
	/usr/lib/qt6/libexec/uic newbottle.ui -o ui_newbottle.h

ui_onscreenkeypad.h: onscreenkeypad.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic onscreenkeypad.ui -o ui_onscreenkeypad.h

ui_onscreenkeyboard.h: onscreenkeyboard.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic onscreenkeyboard.ui -o ui_onscreenkeyboard.h

ui_waterusagetab.h: waterusagetab.ui \
		/usr/lib/qt6/libexec/uic
	/usr/lib/qt6/libexec/uic waterusagetab.ui -o ui_waterusagetab.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		welcometab.h \
		maintab.h \
		settingstab.h \
		tagstab.h \
		waterusagetab.h \
		controlboardinterface.h \
		basestationinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

controlboardinterface.o: controlboardinterface.cpp controlboardinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlboardinterface.o controlboardinterface.cpp

basestationinterface.o: basestationinterface.cpp basestationinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basestationinterface.o basestationinterface.cpp

maintab.o: maintab.cpp maintab.h \
		ui_maintab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maintab.o maintab.cpp

settingstab.o: settingstab.cpp settingstab.h \
		ui_settingstab.h \
		controlboardinterface.h \
		basestationinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingstab.o settingstab.cpp

tagstab.o: tagstab.cpp tagstab.h \
		ui_tagstab.h \
		newbottle.h \
		controlboardinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tagstab.o tagstab.cpp

welcometab.o: welcometab.cpp welcometab.h \
		ui_welcometab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o welcometab.o welcometab.cpp

newbottle.o: newbottle.cpp newbottle.h \
		ui_newbottle.h \
		onscreenkeyboard.h \
		onscreenkeypad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newbottle.o newbottle.cpp

onscreenkeypad.o: onscreenkeypad.cpp onscreenkeypad.h \
		ui_onscreenkeypad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onscreenkeypad.o onscreenkeypad.cpp

onscreenkeyboard.o: onscreenkeyboard.cpp onscreenkeyboard.h \
		ui_onscreenkeyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onscreenkeyboard.o onscreenkeyboard.cpp

waterusagetab.o: waterusagetab.cpp waterusagetab.h \
		ui_waterusagetab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waterusagetab.o waterusagetab.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_controlboardinterface.o: moc_controlboardinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controlboardinterface.o moc_controlboardinterface.cpp

moc_basestationinterface.o: moc_basestationinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basestationinterface.o moc_basestationinterface.cpp

moc_maintab.o: moc_maintab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maintab.o moc_maintab.cpp

moc_settingstab.o: moc_settingstab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingstab.o moc_settingstab.cpp

moc_tagstab.o: moc_tagstab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tagstab.o moc_tagstab.cpp

moc_welcometab.o: moc_welcometab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_welcometab.o moc_welcometab.cpp

moc_newbottle.o: moc_newbottle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newbottle.o moc_newbottle.cpp

moc_onscreenkeypad.o: moc_onscreenkeypad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_onscreenkeypad.o moc_onscreenkeypad.cpp

moc_onscreenkeyboard.o: moc_onscreenkeyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_onscreenkeyboard.o moc_onscreenkeyboard.cpp

moc_waterusagetab.o: moc_waterusagetab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waterusagetab.o moc_waterusagetab.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/root || mkdir -p $(INSTALL_ROOT)/home/root
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/root/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

